date



DIR_PATH=../../logs/pagefault-persist-logs
mkdir -p $DIR_PATH



NPHJ_SC_PREPOPULATE_NVM_LOG=$DIR_PATH/nphj_sc_prepopulate_nvm.log
rm $NPHJ_SC_PREPOPULATE_NVM_LOG
RDX_BC_PREPOPULATE_NVM_LOG=$DIR_PATH/rdx_bc_prepopulate_nvm.log
rm $RDX_BC_PREPOPULATE_NVM_LOG
RDX_HRO_PREPOPULATE_NVM_LOG=$DIR_PATH/rdx_hro_prepopulate_nvm.log
rm $RDX_HRO_PREPOPULATE_NVM_LOG
cd ../../
./clean.sh
mkdir build
cd build
cmake .. -DTRIAL_NUM=6 -DCLFLUSH=false -DCLFLUSHOPT=false -DNT_STORE=false -DENABLE_FENCE=false -DRUN_PAYLOAD=false -DTUPLE_T_SIZE=16 -DRUN_BILLION=false -DRUN_FNDLY=false -DUSE_PAPI=false -DUSE_PMWATCH=false -DWARMUP=true -DUN_PREPOPULATE=false -DSYNCSTATS=false -DPHJ_SYNCSTATS=false -DUSE_HYPERTHREADING=true -DUSE_NVM=true -DUSE_HUGE=false -DTHREAD_NUM=20 -DBUILDPART_THREAD_NUM=12 -DBUILDPART_WRITE_THREAD_NUM=11 -DPROBEJOIN_THREAD_NUM=20 -DUSE_NUMA=false -DPREFETCH_DISTANCE=32 -DPREFETCH_CACHE=false -DPREFETCH_CACHE_NVM=false -DLOCK_IN_BUCKET=false -DNUM_RADIX_BITS=11 -DNUM_RADIX_BITS_PASS1=12 -DNUM_PASSES=1 -DPHJ_MBP=false -DTEST_PARTITIONING=false -DOUTPUT_OFFSET_NVM=false -DUSE_SWWCB_OPTIMIZED_PART=true -DUSE_SWWCB_OPTIMIZED_PART_ON_NVM=false -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER=true -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER_ON_NVM=false -DSKEW_HANDLING=false -DBW_REG=true -DNONTEMP_STORE_MATER=true -DNONTEMP_STORE_MATER_ON_NVM=false
make -j 32
cd ../scripts/pagefault-persist-scripts
numactl --membind=0 ../../bin/main --algo=phj_radix_bc --workload=uniform --subtype=A --param=pkfk >> $RDX_BC_PREPOPULATE_NVM_LOG
numactl --membind=0 ../../bin/main --algo=phj_radix_hro --workload=uniform --subtype=A --param=pkfk >> $RDX_HRO_PREPOPULATE_NVM_LOG
cd ../../
./clean.sh
mkdir build
cd build
cmake .. -DTRIAL_NUM=6 -DCLFLUSH=false -DCLFLUSHOPT=false -DNT_STORE=false -DENABLE_FENCE=false -DRUN_PAYLOAD=false -DTUPLE_T_SIZE=16 -DRUN_BILLION=false -DRUN_FNDLY=false -DUSE_PAPI=false -DUSE_PMWATCH=false -DWARMUP=true -DUN_PREPOPULATE=false -DSYNCSTATS=false -DPHJ_SYNCSTATS=false -DUSE_HYPERTHREADING=true -DUSE_NVM=true -DUSE_HUGE=false -DTHREAD_NUM=20 -DBUILDPART_THREAD_NUM=20 -DBUILDPART_WRITE_THREAD_NUM=11 -DPROBEJOIN_THREAD_NUM=20 -DUSE_NUMA=false -DPREFETCH_DISTANCE=32 -DPREFETCH_CACHE=false -DPREFETCH_CACHE_NVM=false -DLOCK_IN_BUCKET=false -DNUM_RADIX_BITS=11 -DNUM_RADIX_BITS_PASS1=12 -DNUM_PASSES=1 -DPHJ_MBP=false -DTEST_PARTITIONING=false -DOUTPUT_OFFSET_NVM=false -DUSE_SWWCB_OPTIMIZED_PART=true -DUSE_SWWCB_OPTIMIZED_PART_ON_NVM=false -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER=true -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER_ON_NVM=false -DSKEW_HANDLING=false -DBW_REG=true -DNONTEMP_STORE_MATER=true -DNONTEMP_STORE_MATER_ON_NVM=false
make -j 32
cd ../scripts/pagefault-persist-scripts
numactl --membind=0 ../../bin/main --algo=nphj_sc --workload=uniform --subtype=A --param=pkfk >> $NPHJ_SC_PREPOPULATE_NVM_LOG




NPHJ_SC_UNPREPOPULATE_NVM_LOG=$DIR_PATH/nphj_sc_unprepopulate_nvm.log
rm $NPHJ_SC_UNPREPOPULATE_NVM_LOG
RDX_BC_UNPREPOPULATE_NVM_LOG=$DIR_PATH/rdx_bc_unprepopulate_nvm.log
rm $RDX_BC_UNPREPOPULATE_NVM_LOG
RDX_HRO_UNPREPOPULATE_NVM_LOG=$DIR_PATH/rdx_hro_unprepopulate_nvm.log
rm $RDX_HRO_UNPREPOPULATE_NVM_LOG
cd ../../
./clean.sh
mkdir build
cd build
cmake .. -DTRIAL_NUM=6 -DCLFLUSH=false -DCLFLUSHOPT=false -DNT_STORE=false -DENABLE_FENCE=false -DRUN_PAYLOAD=false -DTUPLE_T_SIZE=16 -DRUN_BILLION=false -DRUN_FNDLY=false -DUSE_PAPI=false -DUSE_PMWATCH=false -DWARMUP=true -DUN_PREPOPULATE=true -DSYNCSTATS=false -DPHJ_SYNCSTATS=false -DUSE_HYPERTHREADING=true -DUSE_NVM=true -DUSE_HUGE=false -DTHREAD_NUM=20 -DBUILDPART_THREAD_NUM=12 -DBUILDPART_WRITE_THREAD_NUM=11 -DPROBEJOIN_THREAD_NUM=20 -DUSE_NUMA=false -DPREFETCH_DISTANCE=32 -DPREFETCH_CACHE=false -DPREFETCH_CACHE_NVM=false -DLOCK_IN_BUCKET=false -DNUM_RADIX_BITS=11 -DNUM_RADIX_BITS_PASS1=12 -DNUM_PASSES=1 -DPHJ_MBP=false -DTEST_PARTITIONING=false -DOUTPUT_OFFSET_NVM=false -DUSE_SWWCB_OPTIMIZED_PART=true -DUSE_SWWCB_OPTIMIZED_PART_ON_NVM=false -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER=true -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER_ON_NVM=false -DSKEW_HANDLING=false -DBW_REG=true -DNONTEMP_STORE_MATER=true -DNONTEMP_STORE_MATER_ON_NVM=false
make -j 32
cd ../scripts/pagefault-persist-scripts
numactl --membind=0 ../../bin/main --algo=eth_pro --workload=uniform --subtype=A --param=pkfk >> $RDX_BC_UNPREPOPULATE_NVM_LOG
numactl --membind=0 ../../bin/main --algo=eth_prho --workload=uniform --subtype=A --param=pkfk >> $RDX_HRO_UNPREPOPULATE_NVM_LOG
cd ../../
./clean.sh
mkdir build
cd build
cmake .. -DTRIAL_NUM=6 -DCLFLUSH=false -DCLFLUSHOPT=false -DNT_STORE=false -DENABLE_FENCE=false -DRUN_PAYLOAD=false -DTUPLE_T_SIZE=16 -DRUN_BILLION=false -DRUN_FNDLY=false -DUSE_PAPI=false -DUSE_PMWATCH=false -DWARMUP=true -DUN_PREPOPULATE=true -DSYNCSTATS=false -DPHJ_SYNCSTATS=false -DUSE_HYPERTHREADING=true -DUSE_NVM=true -DUSE_HUGE=false -DTHREAD_NUM=20 -DBUILDPART_THREAD_NUM=20 -DBUILDPART_WRITE_THREAD_NUM=11 -DPROBEJOIN_THREAD_NUM=20 -DUSE_NUMA=false -DPREFETCH_DISTANCE=32 -DPREFETCH_CACHE=false -DPREFETCH_CACHE_NVM=false -DLOCK_IN_BUCKET=false -DNUM_RADIX_BITS=11 -DNUM_RADIX_BITS_PASS1=12 -DNUM_PASSES=1 -DPHJ_MBP=false -DTEST_PARTITIONING=false -DOUTPUT_OFFSET_NVM=false -DUSE_SWWCB_OPTIMIZED_PART=true -DUSE_SWWCB_OPTIMIZED_PART_ON_NVM=false -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER=true -DUSE_SWWCB_OPTIMIZED_RADIX_CLUSTER_ON_NVM=false -DSKEW_HANDLING=false -DBW_REG=true -DNONTEMP_STORE_MATER=true -DNONTEMP_STORE_MATER_ON_NVM=false
make -j 32
cd ../scripts/pagefault-persist-scripts
numactl --membind=0 ../../bin/main --algo=nphj_sc --workload=uniform --subtype=A --param=pkfk >> $NPHJ_SC_UNPREPOPULATE_NVM_LOG


cd ../../
./clean.sh



date